### ISSUE TITLE
How to launch

### ISSUE THREAD

**Issue by Priednis** [Tairraos/vscode-local-web-opener#1]
Hi,
maybe a stupid question from a noob, but how do I invoke your plugin. That is - If I have a html page - either open in the editor or visible in the opened directory, how to open that in the web browser with your plugin?

**Comment by Priednis** [comment]
Duh, found it (I think I did not see it immediately after restart)...
**Right-Click in the Explorer or right-click in the editor window and "Open in local web".**

I guess I expected it also with right-click on the Document tab (where the filename is shown).

**Comment by Tairraos** [comment]
Sorry for my poor readme, i will push more info into later. 
It should be install to vscode first(search `local web opener` in the extension market)
after reload vscode, we can see context menu `open in local web` both on right click file list or tab name. it will open a browser with selected file with `file:///User/xiaole/Workspace/testsite/index.html` by default. 
then, go to `setting -> extension -> Local web opener`, should see 2 patten fields. the plugins will modify the "file://xxxx“, replace the first patten with the 2nd patten

the original URL is the absolute path of file, like `/User/xiaole/Workspace/testsite/index.html`
i created a symbol link for `/User/xiaole/Workspace` named `project` in `/Library/WebServer/Documents` (it is my local web server DocumentRoot)

so i set the 1st patten as `/User/Xiaole/Workspace`
set the 2nd patten as `http://local.server.com/project` (there is `127.0.0.1  local.server.com` in `/etc/hosts`)

retry the context menu, `open local web`, now browser open the page with the url `http://local.server.com/project/testsite/index.html`
